//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigBee.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZigBee.Strings.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available ZigBees.
        /// </summary>
        public static string MainWindowExpanderTitle {
            get {
                return ResourceManager.GetString("MainWindowExpanderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load project map.
        /// </summary>
        public static string MainWindowManuHeaderProjectLoadMap {
            get {
                return ResourceManager.GetString("MainWindowManuHeaderProjectLoadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindowMenuAbout {
            get {
                return ResourceManager.GetString("MainWindowMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ZigBee Network Manager.
        /// </summary>
        public static string MainWindowMenuHeaderAddZigBeeNetworkManager {
            get {
                return ResourceManager.GetString("MainWindowMenuHeaderAddZigBeeNetworkManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MainWindowMenuHeaderNew {
            get {
                return ResourceManager.GetString("MainWindowMenuHeaderNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string MainWindowMenuHeaderProject {
            get {
                return ResourceManager.GetString("MainWindowMenuHeaderProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Network.
        /// </summary>
        public static string MainWindowMenuHeaderProjectAddNetwork {
            get {
                return ResourceManager.GetString("MainWindowMenuHeaderProjectAddNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ZigBee.
        /// </summary>
        public static string MainWindowMenuHeaderProjectAddZigBee {
            get {
                return ResourceManager.GetString("MainWindowMenuHeaderProjectAddZigBee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit project.
        /// </summary>
        public static string MainWindowMenuHeaderProjectEdit {
            get {
                return ResourceManager.GetString("MainWindowMenuHeaderProjectEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load project.
        /// </summary>
        public static string MainWindowMenuHeaderProjectLoad {
            get {
                return ResourceManager.GetString("MainWindowMenuHeaderProjectLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        public static string MainWindowMenuHeaderProjectSave {
            get {
                return ResourceManager.GetString("MainWindowMenuHeaderProjectSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select library.
        /// </summary>
        public static string SelectLibrary {
            get {
                return ResourceManager.GetString("SelectLibrary", resourceCulture);
            }
        }
    }
}
