//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NecBlik.Core.GUI.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NecBlik.Core.GUI.Strings.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000000 (Broadcast).
        /// </summary>
        public static string Broadcast {
            get {
                return ResourceManager.GetString("Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string GPAddress {
            get {
                return ResourceManager.GetString("GPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add rule.
        /// </summary>
        public static string GPAddRuleCommand {
            get {
                return ResourceManager.GetString("GPAddRuleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache ID.
        /// </summary>
        public static string GPCacheId {
            get {
                return ResourceManager.GetString("GPCacheId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filters.
        /// </summary>
        public static string GPClearFilters {
            get {
                return ResourceManager.GetString("GPClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear rules.
        /// </summary>
        public static string GPClearRulesCommand {
            get {
                return ResourceManager.GetString("GPClearRulesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device unavailable.
        /// </summary>
        public static string GPDeviceUnavailable {
            get {
                return ResourceManager.GetString("GPDeviceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        public static string GPFactory {
            get {
                return ResourceManager.GetString("GPFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string GPFilters {
            get {
                return ResourceManager.GetString("GPFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string GPFrom {
            get {
                return ResourceManager.GetString("GPFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        public static string GPGuid {
            get {
                return ResourceManager.GetString("GPGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string GPMessage {
            get {
                return ResourceManager.GetString("GPMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string GPms {
            get {
                return ResourceManager.GetString("GPms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GPName {
            get {
                return ResourceManager.GetString("GPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string GPOpen {
            get {
                return ResourceManager.GetString("GPOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload.
        /// </summary>
        public static string GPPayload {
            get {
                return ResourceManager.GetString("GPPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload size.
        /// </summary>
        public static string GPPayloadSize {
            get {
                return ResourceManager.GetString("GPPayloadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string GPPing {
            get {
                return ResourceManager.GetString("GPPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping packet.
        /// </summary>
        public static string GPPingPacket {
            get {
                return ResourceManager.GetString("GPPingPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string GPProperty {
            get {
                return ResourceManager.GetString("GPProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieved.
        /// </summary>
        public static string GPRecieved {
            get {
                return ResourceManager.GetString("GPRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response time.
        /// </summary>
        public static string GPResponseTime {
            get {
                return ResourceManager.GetString("GPResponseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string GPResult {
            get {
                return ResourceManager.GetString("GPResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned.
        /// </summary>
        public static string GPReturned {
            get {
                return ResourceManager.GetString("GPReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string GPRun {
            get {
                return ResourceManager.GetString("GPRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string GPSelect {
            get {
                return ResourceManager.GetString("GPSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote address.
        /// </summary>
        public static string GPSelectedRemoteAddress {
            get {
                return ResourceManager.GetString("GPSelectedRemoteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string GPSent {
            get {
                return ResourceManager.GetString("GPSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string GPStatus {
            get {
                return ResourceManager.GetString("GPStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string GPTimeout {
            get {
                return ResourceManager.GetString("GPTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string GPTo {
            get {
                return ResourceManager.GetString("GPTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string GPValue {
            get {
                return ResourceManager.GetString("GPValue", resourceCulture);
            }
        }
    }
}
