//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NecBlik.Digi.GUI.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NecBlik.Digi.GUI.Strings.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant&apos;t send from remote device..
        /// </summary>
        public static string CantSendFromRemoteDevices {
            get {
                return ResourceManager.GetString("CantSendFromRemoteDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string GPAdd {
            get {
                return ResourceManager.GetString("GPAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT Commands.
        /// </summary>
        public static string GPATCommands {
            get {
                return ResourceManager.GetString("GPATCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud rate.
        /// </summary>
        public static string GPBaudRate {
            get {
                return ResourceManager.GetString("GPBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GPCancel {
            get {
                return ResourceManager.GetString("GPCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string GPCommand {
            get {
                return ResourceManager.GetString("GPCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string GPConfirm {
            get {
                return ResourceManager.GetString("GPConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator class.
        /// </summary>
        public static string GPCoordinatorType {
            get {
                return ResourceManager.GetString("GPCoordinatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current value.
        /// </summary>
        public static string GPCurrentValue {
            get {
                return ResourceManager.GetString("GPCurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GPDescription {
            get {
                return ResourceManager.GetString("GPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string GPDiagnostics {
            get {
                return ResourceManager.GetString("GPDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last poll.
        /// </summary>
        public static string GPLastPoll {
            get {
                return ResourceManager.GetString("GPLastPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local range.
        /// </summary>
        public static string GPLocalRange {
            get {
                return ResourceManager.GetString("GPLocalRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean.
        /// </summary>
        public static string GPMean {
            get {
                return ResourceManager.GetString("GPMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GPName {
            get {
                return ResourceManager.GetString("GPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network name.
        /// </summary>
        public static string GPNetworkName {
            get {
                return ResourceManager.GetString("GPNetworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network class.
        /// </summary>
        public static string GPNetworkType {
            get {
                return ResourceManager.GetString("GPNetworkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string GPParameter {
            get {
                return ResourceManager.GetString("GPParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload size.
        /// </summary>
        public static string GPPayloadSize {
            get {
                return ResourceManager.GetString("GPPayloadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID.
        /// </summary>
        public static string GPPID {
            get {
                return ResourceManager.GetString("GPPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string GPPleaseWait {
            get {
                return ResourceManager.GetString("GPPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string GPRange {
            get {
                return ResourceManager.GetString("GPRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote address.
        /// </summary>
        public static string GPRemoteAddress {
            get {
                return ResourceManager.GetString("GPRemoteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote range.
        /// </summary>
        public static string GPRemoteRange {
            get {
                return ResourceManager.GetString("GPRemoteRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string GPSelect {
            get {
                return ResourceManager.GetString("GPSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select port.
        /// </summary>
        public static string GPSelectPort {
            get {
                return ResourceManager.GetString("GPSelectPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string GPSend {
            get {
                return ResourceManager.GetString("GPSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial port.
        /// </summary>
        public static string GPSerialPort {
            get {
                return ResourceManager.GetString("GPSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string GPStart {
            get {
                return ResourceManager.GetString("GPStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string GPStop {
            get {
                return ResourceManager.GetString("GPStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string GPTemperature {
            get {
                return ResourceManager.GetString("GPTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throughput.
        /// </summary>
        public static string GPThroughput {
            get {
                return ResourceManager.GetString("GPThroughput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VID.
        /// </summary>
        public static string GPVID {
            get {
                return ResourceManager.GetString("GPVID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a custom view model for your coordinator. Leave empty if you do not have one..
        /// </summary>
        public static string TTCoordinatorClass {
            get {
                return ResourceManager.GetString("TTCoordinatorClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a custom view model for your network. Leave empty if you do not have one..
        /// </summary>
        public static string TTNetworkClass {
            get {
                return ResourceManager.GetString("TTNetworkClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud rate between serial port controller and your coordinator device..
        /// </summary>
        public static string TTSerialPortBaudRate {
            get {
                return ResourceManager.GetString("TTSerialPortBaudRate", resourceCulture);
            }
        }
    }
}
