//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NecBlik.PyDigi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NecBlik.PyDigi.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Serial Port.
        /// </summary>
        public static string AutoDetectionFilterUSBSerialPort {
            get {
                return ResourceManager.GetString("AutoDetectionFilterUSBSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator.
        /// </summary>
        public static string CoordinatorCachePrefix {
            get {
                return ResourceManager.GetString("CoordinatorCachePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator.json.
        /// </summary>
        public static string CoordinatorFile {
            get {
                return ResourceManager.GetString("CoordinatorFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PyDigi Network.
        /// </summary>
        public static string DefaultPyDigiNetworkName {
            get {
                return ResourceManager.GetString("DefaultPyDigiNetworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.json.
        /// </summary>
        public static string NetworkFile {
            get {
                return ResourceManager.GetString("NetworkFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PyDigi coordinator.
        /// </summary>
        public static string PyDefaultDigiCoordinatorName {
            get {
                return ResourceManager.GetString("PyDefaultDigiCoordinatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PyDigi.
        /// </summary>
        public static string PyDigiFactoryId {
            get {
                return ResourceManager.GetString("PyDigiFactoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environments/Python.
        /// </summary>
        public static string PyDigiScriptsLocation {
            get {
                return ResourceManager.GetString("PyDigiScriptsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLL/python39.dll.
        /// </summary>
        public static string PythonDLLSubpath {
            get {
                return ResourceManager.GetString("PythonDLLSubpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environments/Python.
        /// </summary>
        public static string PythonScriptsSearchPath {
            get {
                return ResourceManager.GetString("PythonScriptsSearchPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environments/Python/virtualPythonEnvironment/.
        /// </summary>
        public static string PythonVirtualEnvPath {
            get {
                return ResourceManager.GetString("PythonVirtualEnvPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VirtualEnvInit.py.
        /// </summary>
        public static string ScriptInitialize_py {
            get {
                return ResourceManager.GetString("ScriptInitialize_py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZigBeeCoordinator.py.
        /// </summary>
        public static string ScriptZigBeeCoordinator_py {
            get {
                return ResourceManager.GetString("ScriptZigBeeCoordinator_py", resourceCulture);
            }
        }
    }
}
