//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NecBlik.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NecBlik.Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        public static string AbstractFactoryId {
            get {
                return ResourceManager.GetString("AbstractFactoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string AnyFactoryId {
            get {
                return ResourceManager.GetString("AnyFactoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DefaultFactoryId {
            get {
                return ResourceManager.GetString("DefaultFactoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string GPNetwork {
            get {
                return ResourceManager.GetString("GPNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZigBee.
        /// </summary>
        public static string GPZigBee {
            get {
                return ResourceManager.GetString("GPZigBee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZigBee Coordinator.
        /// </summary>
        public static string GPZigBeeCoordinator {
            get {
                return ResourceManager.GetString("GPZigBeeCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ProjectModelPojectNameDefault {
            get {
                return ResourceManager.GetString("ProjectModelPojectNameDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown PanId.
        /// </summary>
        public static string ZigBeeCoordinatorPanIdDefault {
            get {
                return ResourceManager.GetString("ZigBeeCoordinatorPanIdDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnknownZigbee.
        /// </summary>
        public static string ZigBeeModelNameDefault {
            get {
                return ResourceManager.GetString("ZigBeeModelNameDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Networks.
        /// </summary>
        public static string ZigBeeNetworksDirectory {
            get {
                return ResourceManager.GetString("ZigBeeNetworksDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Sources.
        /// </summary>
        public static string ZigBeeNetworkSourcesSubdirectory {
            get {
                return ResourceManager.GetString("ZigBeeNetworkSourcesSubdirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve address.
        /// </summary>
        public static string ZigBeeUnableToRetrieveAddress {
            get {
                return ResourceManager.GetString("ZigBeeUnableToRetrieveAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown version.
        /// </summary>
        public static string ZigBeeVersionDefault {
            get {
                return ResourceManager.GetString("ZigBeeVersionDefault", resourceCulture);
            }
        }
    }
}
