//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NecBlik.Virtual.GUI.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NecBlik.Virtual.GUI.Strings.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new device address or leave empty to generate one..
        /// </summary>
        public static string EnterAddressOrLeaveEmpty {
            get {
                return ResourceManager.GetString("EnterAddressOrLeaveEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string GPAddress {
            get {
                return ResourceManager.GetString("GPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string GPAdvanced {
            get {
                return ResourceManager.GetString("GPAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GPCancel {
            get {
                return ResourceManager.GetString("GPCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string GPConfirm {
            get {
                return ResourceManager.GetString("GPConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator.
        /// </summary>
        public static string GPCoordinator {
            get {
                return ResourceManager.GetString("GPCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator type.
        /// </summary>
        public static string GPCoordinatorType {
            get {
                return ResourceManager.GetString("GPCoordinatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination address.
        /// </summary>
        public static string GPDestinationAddress {
            get {
                return ResourceManager.GetString("GPDestinationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string GPDevices {
            get {
                return ResourceManager.GetString("GPDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string GPDiscover {
            get {
                return ResourceManager.GetString("GPDiscover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        public static string GPFactory {
            get {
                return ResourceManager.GetString("GPFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string GPFrom {
            get {
                return ResourceManager.GetString("GPFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        public static string GPGuid {
            get {
                return ResourceManager.GetString("GPGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string GPMessage {
            get {
                return ResourceManager.GetString("GPMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GPName {
            get {
                return ResourceManager.GetString("GPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network information.
        /// </summary>
        public static string GPNetworkInformation {
            get {
                return ResourceManager.GetString("GPNetworkInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network name.
        /// </summary>
        public static string GPNetworkName {
            get {
                return ResourceManager.GetString("GPNetworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PanId.
        /// </summary>
        public static string GPNetworkPanId {
            get {
                return ResourceManager.GetString("GPNetworkPanId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network type.
        /// </summary>
        public static string GPNetworkType {
            get {
                return ResourceManager.GetString("GPNetworkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string GPOpen {
            get {
                return ResourceManager.GetString("GPOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieved.
        /// </summary>
        public static string GPRecieved {
            get {
                return ResourceManager.GetString("GPRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string GPRules {
            get {
                return ResourceManager.GetString("GPRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string GPSelect {
            get {
                return ResourceManager.GetString("GPSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to map.
        /// </summary>
        public static string GPSendToMap {
            get {
                return ResourceManager.GetString("GPSendToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay open.
        /// </summary>
        public static string GPStayOpen {
            get {
                return ResourceManager.GetString("GPStayOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize.
        /// </summary>
        public static string GPSynchronize {
            get {
                return ResourceManager.GetString("GPSynchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string GPVersion {
            get {
                return ResourceManager.GetString("GPVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual devices count.
        /// </summary>
        public static string GPVirtualDevicesCount {
            get {
                return ResourceManager.GetString("GPVirtualDevicesCount", resourceCulture);
            }
        }
    }
}
